name: test
on: push

jobs:
  coverage:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: install
        run: npm i
      - name: test
        run: npm run test
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
